config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"

  resources :home, only: [:index]

  get :about, to: 'home#about', as: :about
  get :career, to: 'home#career', as: :career
  get :contact, to: 'home#contact', as: :contact
  get :projects, to: 'home#projects', as: :projects
  get :skills, to: 'home#skills', as: :skills
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :render_content, only: %i[about career skills projects contact]

  def about; end

  def career; end

  def skills; end

  def projects; end

  def contact; end

  def render_content
    respond_to do |format|
      format.html
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update(:content, partial: "home/#{action_name}/content"),
          turbo_stream.update(:navigation,
                              partial: 'shared/navigation',
                              locals: { selected: action_name }),
        ]
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def image_style(path)
    "background-image: url('#{image_path(path)}');"
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def selected?(selected, value)
    selected.to_s == value.to_s
  end
end

app/views/home/about.html.erb
<%= render 'home/about/content' %>

app/views/home/about/_content.html.erb
<div class="flex flex-1 gap-10 p-10">
  <div class="flex flex-col flex-1 gap-5">
    <%= render 'shared/header', header: 'About Me' %>

    <div class="flex flex-1">
      <div class="flex flex-1">
        <div class="flex-1">
          "Hello! I'm [Your Name], a passionate software engineer specializing in web development and cloud computing. With a strong background in coding and problem-solving, I aim to create efficient and scalable software solutions. Welcome to my personal resume website!"
        </div>
      </div>
    </div>
  </div>

  <div class="flex flex-1 relative max-w-[40%]">
    <div class="absolute right-0 top-0 rounded-lg shadow bg-secondary h-[calc(100%-1rem)] w-[calc(100%-1rem)] "></div>
    <div class="absolute left-0 bottom-0 rounded-lg shadow bg-no-repeat bg-cover bg-center h-[calc(100%-1rem)] w-[calc(100%-1rem)]"
         style="<%= image_style('railing_side.jpg') %>"></div>
  </div>
</div>

app/views/home/career.html.erb
<%= render 'home/career/content' %>

app/views/home/career/_content.html.erb
<div class="flex flex-1 gap-10 p-10">
  <div class="flex flex-col flex-1 gap-10">
    <%= render 'shared/header', header: 'Career' %>

    <div class="flex flex-col gap-5">
      <div class="flex flex-1 gap-5">
        <div class="text-xl text-gray-400 pt-[1rem]" style="writing-mode: vertical-rl; text-orientation: sideways;">
          Education
        </div>

        <div class="flex flex-col flex-1 gap-5 bg-base rounded-lg p-5 shadow-inner">
          <%= render 'home/career/education',
                     school: 'Arizona State University',
                     study: 'B.S. Computer Science',
                     date: '2021',
                     image: 'asu.png' %>
        </div>
      </div>

      <div class="flex flex-1 gap-5">
        <div class="text-xl text-gray-400 pt-[1rem]" style="writing-mode: vertical-rl; text-orientation: sideways;">
          Experience
        </div>

        <div class="flex flex-col flex-1 gap-5 bg-base rounded-lg p-5 shadow-inner">
          <%= render 'home/career/experience',
                     position: 'Senior Software Engineer',
                     company: 'StrongMind',
                     date_range: '2024 - Present',
                     image: 'strongmind.png' %>

          <%= render 'home/career/experience',
                     position: 'Software Engineer',
                     company: 'StrongMind',
                     date_range: '2022 - 2024',
                     image: 'strongmind.png' %>

          <%= render 'home/career/experience',
                     position: 'Junior Software Engineer',
                     company: 'StrongMind',
                     date_range: '2021 - 2022',
                     image: 'strongmind.png' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/career/_education.html.erb
<%= render 'shared/card' do %>
  <div class="flex flex-1 items-center p-5 gap-5 text-neutral max-h-[5rem]">
    <div class="w-[6rem] h-[2.4rem] bg-contain bg-no-repeat bg-center" style="<%= image_style(local_assigns[:image]) %>"></div>

    <div class="flex flex-col justify-center">
      <div class="text-lg"> <%= local_assigns[:school] %> </div>
      <div class="text-sm"> <%= local_assigns[:study] %> </div>
    </div>

    <div class="flex flex-1 justify-end">
      <div class="flex flex-col text-sm">
        <%= local_assigns[:date] %>
      </div>
    </div>
  </div>
<% end %>

app/views/home/career/_experience.html.erb
<%= render 'shared/card' do %>
  <div class="flex flex-1 items-center p-5 gap-5 text-neutral max-h-[5rem]">
    <div class="w-[2.4rem] h-[2.4rem] bg-contain bg-no-repeat bg-center" style="<%= image_style(local_assigns[:image]) %>"></div>

    <div class="flex flex-col justify-center">
      <div class="text-lg"> <%= local_assigns[:position] %> </div>
      <div class="text-sm"> <%= local_assigns[:company] %> </div>
    </div>

    <div class="flex flex-1 justify-end">
      <div class="text-sm"><%= local_assigns[:date_range] %></div>
    </div>
  </div>
<% end %>

app/views/home/contact.html.erb
<%= render 'home/contact/content' %>

app/views/home/contact/_content.html.erb
<div class="flex flex-1 gap-10 p-10">
  <div class="flex flex-col flex-1 gap-5">
    <%= render 'shared/header', header: 'Contact' %>

    <div class="flex flex-1">
      <div class="flex flex-1">
        <div class="flex-1">
          "Hello! I'm [Your Name], a passionate software engineer specializing in web development and cloud computing. With a strong background in coding and problem-solving, I aim to create efficient and scalable software solutions. Welcome to my personal resume website!"
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="flex flex-1">
  <div id="left" class="flex-1 max-w-[20%]"></div>

  <div id="center" class="flex flex-col flex-1">
    <div class="flex-1 max-h-[15%]"></div>

    <div class="flex flex-1">
      <%= render 'shared/card' do %>
        <%= turbo_frame_tag :content, class: 'flex flex-1' do %>
          <%= render 'home/about/content' %>
        <% end %>
      <% end %>
    </div>

    <div class="flex flex-1 max-h-[15%]">
      <%= render 'shared/socials' %>
    </div>
  </div>

  <div id="right" class="flex flex-col flex-1 max-w-[20%]">
    <div class="flex-1 max-h-[15%]"></div>

    <div id="navigation" class="flex flex-1">
      <%= render 'shared/navigation', selected: :about %>
    </div>

    <div class="flex-1 max-h-[15%]"></div>
  </div>
</div>

app/views/home/projects.html.erb
<%= render 'home/projects/content' %>

app/views/home/projects/_content.html.erb
<div class="flex flex-1 gap-10 p-10">
  <div class="flex flex-col flex-1 gap-5">
    <%= render 'shared/header', header: 'Projects' %>

    <div class="flex flex-1">
      <div class="flex flex-1">
        <div class="flex-1">
          "Hello! I'm [Your Name], a passionate software engineer specializing in web development and cloud computing. With a strong background in coding and problem-solving, I aim to create efficient and scalable software solutions. Welcome to my personal resume website!"
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/skills.html.erb
<%= turbo_stream.update(:content) do %>
  <%= render 'home/skills/content' %>
<% end %>

<%= turbo_stream.update(:navigation) do %>
  <%= render 'shared/navigation', selected: :skills  %>
<% end %>

app/views/home/skills.turbo_stream.erb
<%= turbo_stream.update(:content) do %>
  <%= render 'home/skills/content' %>
<% end %>

<%= turbo_stream.update(:navigation) do %>
  <%= render 'shared/navigation', selected: :skills  %>
<% end %>

app/views/home/skills/_content.html.erb
<div class="flex flex-1 gap-10 p-10">
  <div class="flex flex-col flex-1 gap-5">
    <%= render 'shared/header', header: 'Skills' %>

    <div class="flex flex-1 gap-5">
      <div class="text-xl text-gray-400 pt-[1rem]" style="writing-mode: vertical-rl; text-orientation: sideways;">
        Languages
      </div>

      <div class="flex flex-wrap flex-1 gap-5 bg-base rounded-lg p-5 shadow-inner">
        <%= render 'home/skills/skill', icon: 'ruby.png', skill: 'Ruby' %>
        <%= render 'home/skills/skill', icon: 'python.png', skill: 'Python' %>
        <%= render 'home/skills/skill', icon: 'csharp.png', skill: 'C#' %>
        <%= render 'home/skills/skill', icon: 'cplusplus.png', skill: 'C++' %>
        <%= render 'home/skills/skill', icon: 'java.png', skill: 'Java' %>
        <%= render 'home/skills/skill', icon: 'js.png', skill: 'Javascript' %>
        <%= render 'home/skills/skill', icon: 'postgresql.png', skill: 'PostgreSQL' %>
        <%= render 'home/skills/skill', icon: 'html.png', skill: 'HTML' %>
        <%= render 'home/skills/skill', icon: 'css.png', skill: 'CSS' %>
      </div>
    </div>

    <div class="flex flex-1 gap-5">
      <div class="text-xl text-gray-400 pt-[1rem]" style="writing-mode: vertical-rl; text-orientation: sideways;">
        Frameworks
      </div>
      <div class="flex flex-wrap flex-1 gap-5 bg-base rounded-lg p-5 shadow-inner">
        <%= render 'home/skills/skill', icon: 'rails.png', skill: 'Ruby on Rails' %>
        <%= render 'home/skills/skill', icon: 'django.png', skill: 'Django' %>
        <%= render 'home/skills/skill', icon: 'dotnet.png', skill: 'Dotnet' %>
      </div>
    </div>

    <div class="flex flex-1 gap-5">
      <div class="text-xl text-gray-400 pt-[1rem]" style="writing-mode: vertical-rl; text-orientation: sideways;">
        DevOps
      </div>
      <div class="flex flex-wrap flex-1 gap-5 bg-base rounded-lg p-5 shadow-inner">
        <%= render 'home/skills/skill', icon: 'github.png', skill: 'GitHub' %>
        <%= render 'home/skills/skill', icon: 'github_actions.png', skill: 'GitHub Actions' %>
        <%= render 'home/skills/skill', icon: 'aws.png', skill: 'AWS' %>
        <%= render 'home/skills/skill', icon: 'azure.png', skill: 'Azure' %>
        <%= render 'home/skills/skill', icon: 'azure_devops.png', skill: 'Azure DevOps' %>
        <%= render 'home/skills/skill', icon: 'heroku.png', skill: 'Heroku' %>
        <%= render 'home/skills/skill', icon: 'docker.png', skill: 'Docker' %>
      </div>
    </div>
  </div>
</div>

app/views/home/skills/_skill.html.erb
<div class="">
  <%= render 'shared/card' do %>
    <div class="flex items-center px-2">
      <%= image_tag icon, class: 'w-10 p-2' %>
      <div class="text-sm text-neutral px-2">
        <%= skill %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Sonny Huynh</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex h-screen w-screen bg-base">
    <main class="flex flex-1">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_card.html.erb
<div class="flex flex-1 bg-surface rounded-lg shadow">
  <%= yield %>
</div>

app/views/shared/_header.html.erb
<div class="flex">
  <div class="text-4xl">
    <%= local_assigns[:header] %>
  </div>

  <div class="flex flex-1 items-center pl-5">
    <div class="w-full h-[2px] bg-secondary"></div>
  </div>
</div>

app/views/shared/_links.html.erb
<div class="flex flex-1 justify-center text-neutral text-3xl w-[5rem]">
  <div class="flex items-center p-10 gap-5">
    <%= link_to 'https://github.com/shuynh3', target: :_blank,
                class: 'transition duration-100 hover:scale-125' do %>
      <i class="fa-brands fa-github"></i>
    <% end %>

    <%= link_to 'https://www.linkedin.com/in/sonny-huynh-0/', target: :_blank,
                class: 'transition duration-100 hover:scale-125' do %>
      <i class="fa-brands fa-linkedin"></i>
    <% end %>

    <%= link_to 'https://www.instagram.com/sonny.huynh/', target: :_blank,
                class: 'transition duration-100 hover:scale-125' do %>
      <i class="fa-brands fa-instagram"></i>
    <% end %>

    <%= link_to '/', target: :_blank,
                class: 'transition duration-100 hover:scale-125' do %>
      <i class="fa-solid fa-envelope"></i>
    <% end %>

    <%= link_to '/', target: :_blank,
                class: 'transition duration-100 hover:scale-125' do %>
      <i class="fa-solid fa-circle-question"></i>
    <% end %>
  </div>
</div>

app/views/shared/_navigation.html.erb
<%# locals: (selected: nil) -%>

<nav class="flex flex-1 flex-col items-center gap-10 text-neutral">
  <%= render 'shared/navigation/link', path: about_path, selected: selected?(selected, :about) %>
  <%= render 'shared/navigation/link', path: career_path, selected: selected?(selected, :career) %>
  <%= render 'shared/navigation/link', path: skills_path, selected: selected?(selected, :skills) %>
  <%= render 'shared/navigation/link', path: projects_path, selected: selected?(selected, :projects) %>
  <%= render 'shared/navigation/link', path: contact_path, selected: selected?(selected, :contact) %>
</nav>

app/views/shared/_sidebar.html.erb
<nav class="flex flex-col items-center p-10 gap-5 bg-neutral text-white w-[20%]">
  <%= link_to root_path, class: 'flex' do %>
    <div class="p-3 text-3xl">
      Sonny Huynh
    </div>
  <% end %>
  <div class="flex gap-5">
    <%= link_to root_path do %>
      <div class="p-3 text-2xl">
        Home
      </div>
    <% end %>
  </div>
</nav>

app/views/shared/_socials.html.erb
<div class="flex flex-1 justify-center text-neutral text-3xl w-[5rem]">
  <div class="flex items-center p-10 gap-5">
    <%= link_to 'https://github.com/shuynh3', target: :_blank,
                class: 'transition duration-100 hover:scale-125' do %>
      <i class="fa-brands fa-github"></i>
    <% end %>

    <%= link_to 'https://www.linkedin.com/in/sonny-huynh-0/', target: :_blank,
                class: 'transition duration-100 hover:scale-125' do %>
      <i class="fa-brands fa-linkedin"></i>
    <% end %>

    <%= link_to 'https://www.instagram.com/sonny.huynh/', target: :_blank,
                class: 'transition duration-100 hover:scale-125' do %>
      <i class="fa-brands fa-instagram"></i>
    <% end %>

    <%= link_to '/', target: :_blank,
                class: 'transition duration-100 hover:scale-125' do %>
      <i class="fa-solid fa-envelope"></i>
    <% end %>

    <%= link_to '/', target: :_blank,
                class: 'transition duration-100 hover:scale-125' do %>
      <i class="fa-solid fa-circle-question"></i>
    <% end %>
  </div>
</div>

app/views/shared/navigation/_link.html.erb
<%# locals: (path:, selected: false) -%>

<% if selected %>
  <div class="scale-125 cursor-pointer">
    <div class="rounded py-5 px-10 text-6xl relative bg-surface shadow border border-secondary">
      <i class="fa-solid fa-sun"></i>
    </div>
  </div>
<% else %>
  <%= link_to path, class: 'transition duration-100 hover:scale-125 m-[1px]', data: { turbo_stream: true } do %>
    <div class="py-5 rounded px-10 text-6xl relative bg-surface shadow">
      <i class="fa-solid fa-sun"></i>
    </div>
  <% end %>
<% end %>